### ISSUE TITLE
Bug: Not all pods are listed on k8s resources

### ISSUE THREAD

**Issue by Shubham9t9** [devtron-labs/devtron#2895] opened 2023-01-25 07:41 UTC
### 📜 Description

On app details k8s resources tab, all pods are not listed. 

### 👟 Reproduction steps

1. Go to app details page
2. Is will list not all the pods
3. Go to some other resources like replicaset or others, and come back to pods. 
4. Now you can see all the pods

### 👍 Expected behavior

It should list all the pods.

### 👎 Actual Behavior

All pods are not listed.

### ☸ Kubernetes version

Microk8s 1.22

### Cloud provider

<details>
AKS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by Shubham9t9** [comment] 2023-01-25 07:43
![screenshot](https://user-images.githubusercontent.com/87755583/214507155-1d4c2dda-049c-432d-9408-6ac57219b5e7.jpg)

**Comment by Shubham9t9** [comment] 2023-01-25 07:44
![screenshot](https://user-images.githubusercontent.com/87755583/214507155-1d4c2dda-049c-432d-9408-6ac57219b5e7.jpg)

**Comment by Shivam-nagar23** [comment] 2023-09-15 13:37
The issue is not reproducable, might have been fixed till now. @Shubham9t9 have verified this. Please close this issue @prakarsh-dt.

**Closed** 2023-09-20 11:17 UTC
Labels: bug
