### ISSUE TITLE
User (with required permissions) not able to deploy to a specific chart group

### ISSUE THREAD

**Issue by ankit-ls** [devtron-labs/devtron#1027] opened 2021-12-27 11:42 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

One of the users has admin access to:
- Project: `Design Authoring`
- Environment: `beta-staging`
- Chart group: `design-authoring`

Even with all these permissions, he is not able to deploy a chart which is part of `design-authoring` chart group to `beta-staging` environment under project `Design Authoring`. He is getting `Unauthorized` error.

**Expected behavior**

User having the required access for environment, project and chart group should be able to deploy the chart.

**Screenshots**

<img width="448" alt="Screenshot 2021-12-27 at 5 06 28 PM" src="https://user-images.githubusercontent.com/87482092/147468182-6016fffa-5670-4619-959b-be2abde119c7.png">

AB#206

**Comment by prakarsh-dt** [comment] 2022-09-03 07:19
Duplicate of #754

**Comment by deepak-devtron** [comment] 2022-11-14 13:32
This has been fixed and verified , so closing it.

**Closed by deepak-devtron** 2022-11-14 13:32 UTC
Labels: bug, critical
