### ISSUE TITLE
Feature: Support duplication of an environment

### ISSUE THREAD

**Issue by ankit-ls** [devtron-labs/devtron#774] opened 2021-10-06 05:49 UTC
# Summary

We have a usecase where we want to duplicate an environment with all the apps contained in it, with few simple clicks.

# Proposal

We can provide an option in the Global Configs to duplicate an environment.
- It can be a simple form on the UI, asking user to select one of the existing environments.
- On selecting an env, Devtron should list all the apps currently using that env.
- User can select all apps or a selected few for their new environment.
- Once the user clicks on `Duplicate` button, all the apps selected should have a CD pipeline created pointing to new env.
- Every app should also have the same Override configs for the new environment, as was in the original environment.
- Once Duplicated, we can also optionally give a `Deploy All` button on the UI to deploy all the newly created CD pipelines.

AB#416

**Comment by prakarsh-dt** [comment] 2024-07-30 11:44
Duplicate of #4029

**Closed by prakarsh-dt** 2024-07-30 11:44 UTC
Labels: enhancement
