### ISSUE TITLE
Feature: Central dashboard on Devtron UI for dora metrics for all apps

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#5998] opened 2024-10-17 08:42 UTC
### 🔖 Feature description

We want a dashboard where we can see the application dora metrics and set the benchmarks.

### 🎤 Pitch / Usecases

Currently we have dora for per app wise for their environments , But We need the single dashboard for same

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by abhibhaw** [comment] 2024-11-01 06:10
Duplicate of #6012

**Closed by abhibhaw** 2024-11-01 06:10 UTC
Labels: enhancement, ENT-DEY
