### ISSUE TITLE
Enhancement: Upgrade Casbin version to v2

### ISSUE THREAD

**Issue by Shivam-nagar23** [devtron-labs/devtron#5353] opened 2024-06-24 07:58 UTC
### 🔖 Feature description

Upgrade Casbin version to v2

### 🎤 Pitch / Usecases

Upgrade Casbin version to v2

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#10027

**Comment by abhibhaw** [comment] 2024-06-24 09:12
Is this duplicate of #605 @Shivam-nagar23 ?

**Comment by Shivam-nagar23** [comment] 2024-06-24 09:53
@abhibhaw yes, will link issues which will close both .

**Closed** 2024-07-01 11:35 UTC
Labels: enhancement
