### ISSUE TITLE
Bug:  Git sensor got error and return exit code 128

### ISSUE THREAD

**Issue by tommy04062019** [devtron-labs/devtron#5629] opened 2024-08-07 07:06 UTC
### 📜 Description

Logs:
`│ git-sensor {"level":"info","ts":1723014048.660751,"caller":"pkg/RepoManages.go:468","msg":"errored material ","id":4,"errMsg":"exit status 128"}                                                         │
│ git-sensor {"level":"error","ts":1723014050.2870855,"caller":"git/GitBaseManager.go:185","msg":"error in git cli operation","msg":"fatal: not a git repository (or any of the parent directories): .git\ │
│ git-sensor {"level":"error","ts":1723014050.2873294,"caller":"git/RepositoryManager.go:204","msg":"error in updating repository","err":"exit status 128","location":"git@xxxx │
│ git-sensor {"level":"error","ts":1723014050.287529,"caller":"git/Watcher.go:200","msg":"error in fetching material details ","repo":"git@xxxxxxxx","err":"exit s │
│ git-sensor {"level":"error","ts":1723014050.2898335,"caller":"git/GitBaseManager.go:185","msg":"error in git cli operation","msg":"fatal: not in a git directory\n","err":"exit status 128","stacktrace" │
│ git-sensor {"level":"error","ts":1723014050.2899919,"caller":"git/RepositoryManager.go:367","msg":"error in configuring ssh command while adding repo","errorMsg":"","err":"exit status 128","stacktrace │
│ git-sensor {"level":"error","ts":1723014050.2901144,"caller":"git/Watcher.go:212","msg":"error in creating/configuring ssh private key on disk ","repo":"git@xxxxxx │
│ git-sensor {"level":"info","ts":1723014050.4152596,"caller":"pkg/RepoManages.go:468","msg":"errored material ","id":4,"errMsg":"exit status 128"}`

### 👟 Reproduction steps

When I run Build and Deploy. Got an error:
<img width="776" alt="Screenshot 2024-08-07 at 14 05 17" src="https://github.com/user-attachments/assets/2e07102e-2f88-4754-8307-e33107334314">

### 👍 Expected behavior

Pulling code should successfully

### 👎 Actual Behavior

Return code 128

### ☸ Kubernetes version

1.28

### Cloud provider

<details>
openstack
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by ayu-devtron** [comment] 2024-09-17 05:40
Hi @tommy04062019 , If you are still facing this issue then can you please tell us steps to reproduce this ?

**Comment by ayu-devtron** [comment] 2024-09-30 11:55
Hi @tommy04062019 , we believe this error happened because either you didn't have proper access to the target repo or repo url was incorrect. Either way, we have done improvements on our side to show meaningful error messages on UI. 

I am closing this issue for now but feel free to open this if you feel otherwise.

**Closed by ayu-devtron** 2024-09-30 11:55 UTC
Labels: bug
