### ISSUE TITLE
Feature: Base configs for two pipelines

### ISSUE THREAD

**Issue by sagarkt** [devtron-labs/devtron#4366] opened 2023-12-07 07:13 UTC
### 🔖 Feature description

We have two pipelines say prod and dr(disaster recovery). We want some configs to overlap both of the pipelines. This will help to keep configs sync between both the environments.

### 🎤 Pitch

To keep the disaster recovery pipeline in sync with the production pipeline will help to maintain availability of the services.

### ✌️ Solution

There could be an option to add base configs which are merged with the environment specific configs which we set. So if any config is required to be override, that will be done in environment specific configs.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7327

**Comment by prakarsh-dt** [comment] 2023-12-14 12:22
Duplicate of #4393

**Closed by prakarsh-dt** 2023-12-14 12:22 UTC
Labels: enhancement
