### ISSUE TITLE
Support Minio module as integration

### ISSUE THREAD

**Issue by manish-agrawal-ai** [devtron-labs/devtron#2296] opened 2022-09-04 14:00 UTC
# Summary

Minio module should be installed from integrations

# Motivation

Minio stack is heavy. so if user doesn't want minio module then stack installation should be optional

# Proposal

minio should be installed from integrations whenever user needs. 

AB#212

**Comment by anupdhiran** [comment] 2022-09-08 11:23
Duplicate of #2265

**Closed by anupdhiran** 2022-09-08 11:23 UTC
