### ISSUE TITLE
Chart Repo manual sync

### ISSUE THREAD

**Issue by nishant-d** [devtron-labs/devtron#930] opened 2021-12-03 12:06 UTC
# Summary

1. allow user to sync all chart repo manually 
2. sync chart repo when chart repo is added /deleted

# Motivation
currently user has to wait for upto 24 hr to see changes 

# Proposal

trigger sync job when needed

**Comment by pghildiyal** [comment] 2021-12-06 11:54
closed as duplicate of 
devtron-labs/devtron/#935

**Closed by pghildiyal** 2021-12-06 11:54 UTC
Labels: enhancement
