### ISSUE TITLE
Sequential deployent pipeline UI changes

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#1164] opened 2022-01-31 05:38 UTC
# Summary

What change you think needs making.

# Motivation

Please give examples of your use case, e.g. when would you use this.

# Proposal

How do you think this should be implemented?

**Comment by anupdhiran** [comment] 2022-02-14 05:49
Duplicate of #1210. Closing.

**Closed by anupdhiran** 2022-02-14 05:49 UTC
Labels: enhancement
