### ISSUE TITLE
Option to override dockerfile and container registry

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#1986] opened 2022-07-08 06:19 UTC
# Summary

An option to override container registry and dockerfile for different workflows or build pipelines so that it's possible to test on new environment or dockerfile without touching the existing or working ones

# Motivation

We may be deploying on different clouds for different environments but application remains same so this would be helpful

# Proposal

It can be implemented same as we have options to override docker build arguments for different build pipelines

**Comment by prakarsh-dt** [comment] 2022-08-24 13:15
Duplicate of #1241

**Closed by prakarsh-dt** 2022-08-24 13:15 UTC
Labels: enhancement
