### ISSUE TITLE
Feature: show all CI's linked through main CI   

### ISSUE THREAD

**Issue by rupinSec** [devtron-labs/devtron#4669] opened 2024-02-14 08:34 UTC
### 🔖 Feature description

We can show all the CI's and their respective CD and CD's status which are linked through the main CI ( linked CI). This would help in better visibility in case of linked CI and typically in case of more than 10 linked CI through a single CI.  

<img width="362" alt="Screenshot 2024-02-14 at 2 01 43 PM" src="https://github.com/devtron-labs/devtron/assets/44662963/12cd0d7f-8fad-43bc-9c63-c2404a65828f">

We can show all the linked CI through this CI.

### 🎤 Pitch / Usecases

<img width="362" alt="Screenshot 2024-02-14 at 2 01 43 PM" src="https://github.com/devtron-labs/devtron/assets/44662963/3d889d02-90f7-4054-a3ab-1a0c6faed185">

### 👀 Have you spent some time to check if this issue has been raised before?

- [ ] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [ ] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#8513

**Comment by abhibhaw** [comment] 2024-02-14 09:39
@rupinSec Is this a duplicate of #116 ?

**Comment by rupinSec** [comment] 2024-02-15 06:32
@abhibhaw Yes this is duplicate of #116

**Comment by abhibhaw** [comment] 2024-02-15 08:41
Closing because duplicate

**Closed by abhibhaw** 2024-02-15 08:41 UTC
Labels: enhancement, ENT-SPN
