### ISSUE TITLE
Bug: Git sensor was restarted with panic error .

### ISSUE THREAD

**Issue by ajaydevtron** [devtron-labs/devtron#4500] opened 2024-01-03 13:20 UTC
### 📜 Description

Currently Git sensor is deployed on hash (4f3b9a14 ) was restarted with below error .

panic: runtime error: index out of range [65533] with length 62021
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: goroutine 13057991 [running]:
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).DiffCharsToLines(0xc000cab180, {0xc0001b2030, 0x1, 0x0}, {0xc003b82000, 0xf245, 0x13000})
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go:452 +0x2bb
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/utils/diff.DoWithTimeout({0x0, 0xc0026297f0}, {0xc002312000, 0x200}, 0x7fc1b9032108)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/utils/diff/diff.go:37 +0x12a
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/utils/diff.Do(...)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/utils/diff/diff.go:22
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/plumbing/object.filePatchWithContext({0xe44ea8, 0xc000120000}, 0xc001681b00)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/patch.go:68 +0x192
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/plumbing/object.getPatchContext({0xe44ea8, 0xc000120000}, {0x0, 0x0}, {0xc0008a6a00, 0x20, 0xc0019601e0})
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/patch.go:38 +0xf4
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/plumbing/object.Changes.PatchContext(...)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/change.go:156
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/plumbing/object.(*Tree).PatchContext(0x9c79afd3b94ee784, {0xe44ea8, 0xc000120000}, 0xe4e0f8)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:334 +0x65
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/plumbing/object.(*Tree).Patch(...)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:321
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/devtron-labs/git-sensor/pkg/git.RepositoryManagerImpl.ChangesSinceByRepositoryForAnalytics({0xc00012ed20, 0xc000010408, 0xc0000408e0}, {0xc00017f980, 0x35}, {0xe23f00, 0xbdab40}, {0xc00070c630, 0x28}, {0xc00070c6c0, ...})
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/pkg/git/RepositoryManager.go:394 +0x3cf
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/devtron-labs/git-sensor/pkg.RepoManagerImpl.GetReleaseChanges({0xc00012ed20, {0xe4da38, 0xc000010400}, {0xe559d0, 0xc00000f668}, {0xe45030, 0xc000010410}, {0xe4d9f0, 0xc000033eb0}, 0xc00000f680, ...}, ...)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/pkg/RepoManages.go:750 +0x19c
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/devtron-labs/git-sensor/api.(*GrpcHandlerImpl).GetChangesInRelease(0xc0002b9590, {0xb5d5fb, 0xc0004ddce0}, 0xc000090820)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/api/GrpcHandler.go:467 +0xbd
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/devtron-labs/protos/gitSensor._GitSensorService_GetChangesInRelease_Handler.func1({0xe44f18, 0xc0004ddcb0}, {0xcb3b80, 0xc000090820})
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/github.com/devtron-labs/protos/gitSensor/service_grpc.pb.go:576 +0x78
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0xe44f18, 0xc0004ddcb0}, {0xcb3b80, 0xc000090820}, 0xc0005fbae8, 0xc000fdcb40)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:107 +0x87
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/devtron-labs/protos/gitSensor._GitSensorService_GetChangesInRelease_Handler({0xd04c60, 0xc0002b9590}, {0xe44f18, 0xc0004ddcb0}, 0xc0002a5730, 0xc000033d10)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/github.com/devtron-labs/protos/gitSensor/service_grpc.pb.go:578 +0x138
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00000c3c0, {0xe55af0, 0xc000261a00}, 0xc00001a7e0, 0xc00032f830, 0x140eb80, 0x0)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/google.golang.org/grpc/server.go:1340 +0xd13
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: google.golang.org/grpc.(*Server).handleStream(0xc00000c3c0, {0xe55af0, 0xc000261a00}, 0xc00001a7e0, 0x0)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/google.golang.org/grpc/server.go:1713 +0xa2a
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: google.golang.org/grpc.(*Server).serveStreams.func1.2()
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/google.golang.org/grpc/server.go:965 +0x98
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: created by google.golang.org/grpc.(*Server).serveStreams.func1
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/google.golang.org/grpc/server.go:963 +0x294
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: panic: runtime error: index out of range [65533] with length 62021
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: goroutine 13057991 [running]:
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).DiffCharsToLines(0xc000cab180, {0xc0001b2030, 0x1, 0x0}, {0xc003b82000, 0xf245, 0x13000})
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go:452 +0x2bb
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/utils/diff.DoWithTimeout({0x0, 0xc0026297f0}, {0xc002312000, 0x200}, 0x7fc1b9032108)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/utils/diff/diff.go:37 +0x12a
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/utils/diff.Do(...)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/utils/diff/diff.go:22
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/plumbing/object.filePatchWithContext({0xe44ea8, 0xc000120000}, 0xc001681b00)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/patch.go:68 +0x192
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/plumbing/object.getPatchContext({0xe44ea8, 0xc000120000}, {0x0, 0x0}, {0xc0008a6a00, 0x20, 0xc0019601e0})
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/patch.go:38 +0xf4
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/plumbing/object.Changes.PatchContext(...)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/change.go:156
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/plumbing/object.(*Tree).PatchContext(0x9c79afd3b94ee784, {0xe44ea8, 0xc000120000}, 0xe4e0f8)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:334 +0x65
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: gopkg.in/src-d/go-git.v4/plumbing/object.(*Tree).Patch(...)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:321
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/devtron-labs/git-sensor/pkg/git.RepositoryManagerImpl.ChangesSinceByRepositoryForAnalytics({0xc00012ed20, 0xc000010408, 0xc0000408e0}, {0xc00017f980, 0x35}, {0xe23f00, 0xbdab40}, {0xc00070c630, 0x28}, {0xc00070c6c0, ...})
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/pkg/git/RepositoryManager.go:394 +0x3cf
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/devtron-labs/git-sensor/pkg.RepoManagerImpl.GetReleaseChanges({0xc00012ed20, {0xe4da38, 0xc000010400}, {0xe559d0, 0xc00000f668}, {0xe45030, 0xc000010410}, {0xe4d9f0, 0xc000033eb0}, 0xc00000f680, ...}, ...)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/pkg/RepoManages.go:750 +0x19c
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/devtron-labs/git-sensor/api.(*GrpcHandlerImpl).GetChangesInRelease(0xc0002b9590, {0xb5d5fb, 0xc0004ddce0}, 0xc000090820)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/api/GrpcHandler.go:467 +0xbd
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/devtron-labs/protos/gitSensor._GitSensorService_GetChangesInRelease_Handler.func1({0xe44f18, 0xc0004ddcb0}, {0xcb3b80, 0xc000090820})
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/github.com/devtron-labs/protos/gitSensor/service_grpc.pb.go:576 +0x78
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0xe44f18, 0xc0004ddcb0}, {0xcb3b80, 0xc000090820}, 0xc0005fbae8, 0xc000fdcb40)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:107 +0x87
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: github.com/devtron-labs/protos/gitSensor._GitSensorService_GetChangesInRelease_Handler({0xd04c60, 0xc0002b9590}, {0xe44f18, 0xc0004ddcb0}, 0xc0002a5730, 0xc000033d10)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/github.com/devtron-labs/protos/gitSensor/service_grpc.pb.go:578 +0x138
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00000c3c0, {0xe55af0, 0xc000261a00}, 0xc00001a7e0, 0xc00032f830, 0x140eb80, 0x0)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/google.golang.org/grpc/server.go:1340 +0xd13
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: google.golang.org/grpc.(*Server).handleStream(0xc00000c3c0, {0xe55af0, 0xc000261a00}, 0xc00001a7e0, 0x0)
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/google.golang.org/grpc/server.go:1713 +0xa2a
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: google.golang.org/grpc.(*Server).serveStreams.func1.2()
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/google.golang.org/grpc/server.go:965 +0x98
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0: created by google.golang.org/grpc.(*Server).serveStreams.func1
[Jan 03 2024 14:55:54 GMT+0530] git-sensor-0:   /go/src/github.com/devtron-labs/git-sensor/vendor/google.golang.org/grpc/server.go:963 +0x294

### 👟 Reproduction steps

NA

### 👍 Expected behavior

panic error should be handled 

### 👎 Actual Behavior

It was restarted.

### ☸ Kubernetes version

1.23

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7855

**Comment by prakash100198** [comment] 2024-01-17 14:26
Was not able to reproduce, also logging was not proper, so logged some info to monitor later but somehow it's not come on anywhere yet, hence closing this issue currently, if the issue is reported again we can reopen this issue

**Closed by prakash100198** 2024-01-17 14:26 UTC
Labels: bug
