### ISSUE TITLE
Feature: Support deletion of an environment

### ISSUE THREAD

**Issue by ankit-ls** [devtron-labs/devtron#776] opened 2021-10-06 06:40 UTC
# Summary

We would like to delete an environment with all the apps contained in it, with the click of a button.

# Proposal

- We should be able to delete an environment with a single click.
- It should be available in Global Configs only to superadmins. 
- Once clicked on `Delete`, it should delete all the CD pipelines for that particular environment, thereby deleting all the apps in the corresponding namespace.

AB#417

**Comment by prakarsh-dt** [comment] 2024-07-30 11:46
Duplicate of #2499

**Closed by prakarsh-dt** 2024-07-30 11:46 UTC
Labels: enhancement
