### ISSUE TITLE
Inconsistent User access behaviour

### ISSUE THREAD

**Issue by strawhat5** [devtron-labs/devtron#410] opened 2021-04-06 11:32 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

We have observed many inconsistencies in the `User access` section, details of which are added below.

**Current behavior**

1. Assigning direct permission to user fails.
<img width="1280" alt="Screenshot 2021-04-06 at 4 45 18 PM" src="https://user-images.githubusercontent.com/10865861/113703697-d4223700-96f8-11eb-8e05-caa8a0173b37.png">

2. I can assign a group to a user, even though I am not the manager of that group/project. Also, on updation it always gives `Created user successfully` message, even though the user already exists.
<img width="1280" alt="Screenshot 2021-04-06 at 4 48 10 PM" src="https://user-images.githubusercontent.com/10865861/113703756-e4d2ad00-96f8-11eb-8587-e20603dcc017.png">

3. I can unassign a group from a user, even though I am not the manager of that group/project. Gets the same `Created user successfully` message here.
<img width="1280" alt="Screenshot 2021-04-06 at 4 47 24 PM" src="https://user-images.githubusercontent.com/10865861/113703818-f74ce680-96f8-11eb-9447-7fa5a5af08fd.png">

4. Even when I am a manager, I am not able to create groups (with lower permissions) for my own project.
<img width="1280" alt="Screenshot 2021-04-06 at 4 56 53 PM" src="https://user-images.githubusercontent.com/10865861/113704131-60345e80-96f9-11eb-8e11-d5c659187c13.png">

5. Should be able to see the permissions of all groups (View only for non-managers of that group).
<img width="1280" alt="Screenshot 2021-04-06 at 4 57 30 PM" src="https://user-images.githubusercontent.com/10865861/113703992-311ded00-96f9-11eb-86bc-536d8e42b1e9.png">

6. While adding a bunch of users, it gives `User already exists` error (if even one of the users already exists), but successfully creates other users. Which means the `Add User` operation is non-atomic.

**Expected behavior**

All the above inconsistencies should be resolved for a smoother user experience.

**Comment by vikramdevtron** [comment] 2021-04-16 07:02
@strawhat5 issue 1, 4, 5 unable to reproduce, found works as expected.  issue 2 and 3 user message has been fixed, other will be fixed soon, created new ticket for that. 
issue 6, User already exists on bulk creation has fixed in this PR.

**Comment by vikramdevtron** [comment] 2021-04-16 07:02
@strawhat5 issue 1, 4, 5 unable to reproduce, found works as expected.  issue 2 and 3 user message has been fixed, other will be fixed soon, created new ticket for that. 
issue 6, User already exists on bulk creation has fixed in this PR.

**Comment by vikramdevtron** [comment] 2021-04-16 07:02
@strawhat5 issue 1, 4, 5 unable to reproduce, found works as expected.  issue 2 and 3 user message has been fixed, other will be fixed soon, created new ticket for that. 
issue 6, User already exists on bulk creation has fixed in this PR.

**Comment by strawhat5** [comment] 2021-04-16 12:25
@nishant-d Let's connect on this to see if 1, 4, 5 can be reproduced.

**Closed** 2021-04-28 04:36 UTC
Labels: bug
