### ISSUE TITLE
Bug: Caching with buildx doesn't work as expected

### ISSUE THREAD

**Issue by pawan-mehta-dt** [devtron-labs/devtron#2672] opened 2022-11-22 15:43 UTC
### 📜 Description

If we have multiple platforms selected for build using buildx. Then caching works for only one of the platforms and doesn't work for others

### 👟 Reproduction steps

Enable only arm64 in docker build configuration and build without cache once
Then build again to see if it uses cache
Then add another platform amd64 in build configuration and run with or without cache
Then build again to see if it uses cache

### 👍 Expected behavior

It should use caching for both arm64 and amd64 or any number of platforms that we select in build configuration

### 👎 Actual Behavior

It uses cache for only one of the platforms when using multiple platforms and other platforms run all the steps again from scratch. But when only one platform is selected, caching works fine

### ☸ Kubernetes version

KOps 1.21

### Cloud provider

<details>
AWS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by prakash100198** [comment] 2023-02-10 07:22
Tried reproducing at multiple clusters, it seems that this bug has been fixed in some release, so not able to reproduce this issue and the caching is working for all platforms as expected. Hence, closing this ticket for now.

**Closed** 2024-07-26 12:41 UTC
Labels: bug
