### ISSUE TITLE
Set subPath Option not available in Kubernetes External Secret/ConfigMap feature

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#1378] opened 2022-03-21 08:22 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

We do not have an option to set subpath if we want to mount external secret or configmap created using kubectl CLI. Without that we can't mount a file on a directory which already has some existing files. It removes the existing files in the directory

**To Reproduce**

1. Create a secret/configmap using CLI
2. Mount it to a directory which already has some files

**Expected behavior**

File from the secret/configmap should be mounted and existing files should also be there

**Current behavior** 

It removes all the existing files and only the file from secret/configmap is there

**Comment by prakarsh-dt** [comment] 2022-03-24 10:45
Duplicate of #1385

**Closed by prakarsh-dt** 2022-03-24 10:45 UTC
Labels: bug
