### ISSUE TITLE
Showing dropdown to change environment in helm apps

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#1396] opened 2022-03-24 07:14 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

In Helm Apps, it's showing a dropdown to change env as same in devtron apps which is of no use there and is confusing

**Comment by prakarsh-dt** [comment] 2022-03-28 13:24
Duplicate of #1410

**Closed by prakarsh-dt** 2022-03-28 13:24 UTC
Labels: bug
