### ISSUE TITLE
Deployment groups: Page breaks on clicking on Show source info

### ISSUE THREAD

**Issue by uxarya-d** [devtron-labs/devtron#2300] opened 2022-09-05 04:52 UTC
Checklist:

* [x] I've searched in the docs and FAQ for my answer
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Page breaks on clicking on show source info while triggering deployment via deployment groups

**To Reproduce**

1. Create a deployment group
2. Click on [Deploy]
3. Click on 'Show source info' against any image
4. Page breaks

**Expected behavior**

The page should not break and required details should be available.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/6006777d4d3453ae8b648c3d/5c4d2f63-becf-4264-a947-c70e78abdfe3)

![image.png](https://images.zenhubusercontent.com/6006777d4d3453ae8b648c3d/2f772809-c6fa-4e4f-b573-bc0c64d9cdbe)

![image.png](https://images.zenhubusercontent.com/6006777d4d3453ae8b648c3d/c002e46c-f4f6-453c-9663-a28d70484826)

AB#216

**Comment by deepak-devtron** [comment] 2022-09-12 04:46
This is duplicate of https://github.com/devtron-labs/devtron/issues/2299 ,so closing it.

**Closed by deepak-devtron** 2022-09-12 04:46 UTC
Labels: bug
