### ISSUE TITLE
Create an API for getting deployment yaml separately for each deployment

### ISSUE THREAD

**Issue by snehith57624** [devtron-labs/devtron#1137] opened 2022-01-27 09:41 UTC
for version 2 of EA, we need to make separate api to get the manifest separately as the info might be large rather than fetching all deployment history along with the manifest.

**Comment by manish-agrawal-ai** [comment] 2022-01-28 18:48
changed assignee from Snehith to Nishant

**Comment by manish-agrawal-ai** [comment] 2022-01-31 06:28
Duplicate of https://github.com/devtron-labs/devtron/issues/1154

**Closed** 2022-01-31 06:29 UTC
Labels: Task
