### ISSUE TITLE
Append something with repo name for GitOps to keep GitOps repo separate from source code

### ISSUE THREAD

**Issue by dheeth** [devtron-labs/devtron#919] opened 2021-12-02 05:22 UTC
# Summary

If someone uses the same organization in their git which has their source code and on devtron UI they use the same name as repo name, then devtron commits the app values yaml in their source code repository which is not good

# Motivation

Whenever I use the same configuration as above, my source code repo will stay intact and I won't expose anything to the developers

# Proposal

Devtron can append something like `-devtron` to the name of GitOps repos at backend to ensure that a new repo is created everytime user creates a new app

**Comment by nishant-d** [comment] 2021-12-16 11:33
duplicate of https://github.com/devtron-labs/devtron/issues/933

**Closed by nishant-d** 2021-12-16 11:33 UTC
Labels: enhancement
