### ISSUE TITLE
Bug:  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by emoxam** [devtron-labs/devtron#4389] opened 2023-12-12 12:47 UTC
### 📜 Description

I'm trying to build docker image with my jar file
at the devtron log
i see an error that docker is not running

### 👟 Reproduction steps

My pipeline getting source and docker file from bitbucket
then i want it to build docker image and upload it to my nexus docker registry
i guess on the build step it's failing

### 👍 Expected behavior

it builds well

### 👎 Actual Behavior

here's a log
```
21
Login Succeeded

22
2023/12/12 12:10:39 Starting docker build :  docker build  -f Dockerfile --network host -t addressbook .

23
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

24
2023/12/12 12:10:39 exit status 1

25
END_OF_STREAM
```

### ☸ Kubernetes version

1.24.4

### Cloud provider

<details>
on premises
</details>

### 🌍 Browser

Chrome

### 🧱 Your Environment

docker file is
```
FROM openjdk:17-jdk-slim
COPY target/addressBook-0.0.1-SNAPSHOT.jar addressBook.jar
WORKDIR /
EXPOSE 8080
CMD java -Denv=prod -jar addressBook.jar
```

### ✅ Proposed Solution

No idea

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#7443

**Comment by emoxam** [comment] 2023-12-12 12:55
```
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
2023/12/12 12:10:39 DEVTRON  docker file location:  
2023/12/12 12:10:39 Starting docker build :  docker build  -f Dockerfile --network host -t addressbook .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2023/12/12 12:10:39 exit status 1
2023/12/12 12:10:39 DEVTRONci complete event notification done
2023/12/12 12:10:39 DEVTRON housekeeping done. exiting now
2023/12/12 12:10:39 DEVTRON ci complete event notification done
2023/12/12 12:10:39 DEVTRON  housekeeping done. exiting now
2023/12/12 12:10:39 DEVTRON false exit status 1
2023/12/12 12:10:39 DEVTRON not going to upload artifact as storage module not configured...
2023/12/12 12:10:39 DEVTRON exit status 1
2023/12/12 12:10:39 DEVTRON  CI-Runner cleanup executed with exit Code 2 Source_Defer
2023/12/12 12:10:39 DEVTRON  blob storage configured  false
2023/12/12 12:10:39 DEVTRON  in app logging enabled  false
2023/12/12 12:10:39 DEVTRON not uploading logs from app
2023/12/12 12:10:39 DEVTRON  Exiting with exit code  2
time="2023-12-12T12:10:39.415Z" level=info msg="Main container completed"
time="2023-12-12T12:10:39.415Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2023-12-12T12:10:39.415Z" level=info msg="Capturing script exit code"
time="2023-12-12T12:10:39.415Z" level=info msg="Getting exit code of main"
time="2023-12-12T12:10:39.419Z" level=info msg="Get pods 200"
time="2023-12-12T12:10:39.420Z" level=info msg="No output parameters"
time="2023-12-12T12:10:39.420Z" level=info msg="No output artifacts"
time="2023-12-12T12:10:39.420Z" level=info msg="Annotating pod with output"
time="2023-12-12T12:10:39.427Z" level=info msg="Patch pods 200"
time="2023-12-12T12:10:39.436Z" level=info msg="Killing sidecars []"
time="2023-12-12T12:10:39.437Z" level=info msg="Alloc=7723 TotalAlloc=24862 Sys=73297 NumGC=7 Goroutines=10"
```

**Comment by pawan-mehta-dt** [comment] 2023-12-13 11:08
Hi @emoxam which provider are you using to setup devtron? Are there any security policies on host?

**Comment by emoxam** [comment] 2023-12-13 11:18
Hi @prakarsh-dt helm install devtron devtron/devtron-operator --create-namespace --namespace devtroncd --set installer.modules={cicd} --set argo-cd.enabled=true

What is 'security policies' ?

**Comment by pawan-mehta-dt** [comment] 2023-12-13 11:21
@emoxam How did you set the cluster? Any tool you are using for same?

**Comment by emoxam** [comment] 2023-12-13 11:29
@prakarsh-dt Via kubeadm. No such tool at cluster i guess. But we can check, what info do you need ? deployments ? helm charts ?

**Comment by emoxam** [comment] 2023-12-27 13:34
@prakarsh-dt Any updates ?

**Comment by prakarsh-dt** [comment] 2023-12-28 07:24
> @prakarsh-dt Any updates or i can delete devtron ?

Will it be possible for you to get on a call with us for us to figure out the underlying issue you're facing?
Please join our discord server at https://discord.devtron.ai and drop us a message in #setup-and-installation channel.

**Comment by abhibhaw** [comment] 2024-02-14 12:31
Duplicate of #719 fixed with https://github.com/devtron-labs/ci-runner/pull/121

**Closed by abhibhaw** 2024-02-14 12:31 UTC
Labels: bug
