### ISSUE TITLE
Bug: Manifest of cluster level object is not available in application

### ISSUE THREAD

**Issue by rupinSec** [devtron-labs/devtron#2861] opened 2023-01-16 09:00 UTC
### 📜 Description

Manifest is not available for the cluster level objects like PVC is not available in application

### 👟 Reproduction steps

1: Create a application with PVC enabled or manifest given in rawYaml section
2: Deploy the application 
3: We didn't see any manifest of the PVC object created 

### 👍 Expected behavior

Manifest should be available for the cluster level object 

### 👎 Actual Behavior

No manifest is available 

### ☸ Kubernetes version

MicroK8s 1.22

### Cloud provider

MicroK8s running on VM provided by azure 

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

**Comment by vikramdevtron** [comment] 2023-05-15 07:45
duplicate of #2860

**Closed by vikramdevtron** 2023-05-15 07:45 UTC
Labels: bug

**Comment by vikramdevtron** [comment] 2023-05-15 07:47
duplicate of #2860
