### ISSUE TITLE
Feature: Jenkins integration

### ISSUE THREAD

**Issue by vladturbuleasa** [devtron-labs/devtron#4131] opened 2023-10-19 08:45 UTC
### 🔖 Feature description

Would be nice to have Jenkins integration, even Jenkins is old it is still in the blood of a lot of organisations that would avoid changing the Jenkins system for CI part but they would happily adopt devtron if they can re-use parts of their current setup and just switch the CD part to devtron.

- Either create a jenkins plugin that is able to call devtron to deploy a helm to a certain app
- Either allow a API call to devtron to allow enterprise developers to create their own jenkins plugin.

### 🎤 Pitch

Mid-large companies will not want to adopt devtron if they need to change all the systems only to use devtron, like Grafana, would be pretty nice if we can somehow integrate jenkins to trigger deployments to devtron in a easy integrated way, this will open the doors for both parts (devtron as a company and mid-large enterprise that develop for years software and would not want to change current CI system but love to use devtron for CD ).

### ✌️ Solution

Option 1: Create jenkins plugin to integrate to devtron
Option 2: Allow api calls to devtron and document the way we can make a api rest call to trigger it

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#6337

**Comment by prakarsh-dt** [comment] 2023-10-19 10:20
Duplicate of #4040 
@vladturbuleasa This plugin will be released in the upcoming OSS release.

**Closed by prakarsh-dt** 2023-10-19 10:20 UTC
Labels: enhancement
