### ISSUE TITLE
Bug: Helm deployment - helm-chart deployment Timeout for large helm-chart

### ISSUE THREAD

**Issue by jatin-jangir-0220** [devtron-labs/devtron#3547] opened 2023-06-22 05:28 UTC
### 📜 Description

When we deploy large charts using helm deployment 
for example kube-prometheus-stack

in Initial deployment, when the chart take more time for deployment then due to time-out , it do not mark the entry in database, and when we do re-deployment of that chart with same name there it will show the release-name already exist.

### 👟 Reproduction steps

1. go to chart store
2. select chart (large enough to take more time for deployment than timeout)
3. select helm as deployment type (not gitops)
4. deploy helm chart which take large time for initial deployment.
5. when it show error as " it took longer than expexted".
6. in command line : 'helm list -A -a' to list the helm chart and you will see the chart is deployed.

### 👍 Expected behavior

The chart should be added even if the it took longer than expected.

### 👎 Actual Behavior

it show time-out and when we again deploy it show release name already exist.

### ☸ Kubernetes version

Kubernetes -- 1.26 

### Cloud provider

<details>
AKS
</details>

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find any similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/devtron-labs/devtron/blob/main/CODE_OF_CONDUCT.md)

AB#3938

**Comment by prakarsh-dt** [comment] 2023-08-25 12:25
Duplicate of #3482

**Closed by prakarsh-dt** 2023-08-25 12:25 UTC
Labels: bug
